id: P004379
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 11:16:41.515159
source_metadata:
  id: bdr:W24890
  title: གསུང་འབུམ། དགེ་འདུན་དར་རྒྱས
  author: ''
  volumes:
    c069ce7dd162462fbbe104d46b3b4213:
      image_group_id: I6476
      title: ''
      volume_number: 1
      total_pages: 412
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
