id: I59ECFCE6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T11:49:27+00:00'
last_modified: '2022-06-07T22:26:26.464985+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W24890
  title: གསུང་འབུམ། དགེ་འདུན་དར་རྒྱས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    EEEC:
      image_group_id: I6476
      title: ''
      total_pages: 412
      order: 1
      base_file: EEEC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
